apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: controller-manager
  namespace: operator-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:

  # Framework: runtime observation of namespaces & CRDs (addition/deletion).
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]

  # Framework: admission webhook configuration management.
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]

  # Framework: posting the events about the handlers progress/errors.
  - apiGroups: [""]
    resources: [events]
    verbs: [create]

  # Application
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, list, patch, update, watch]

  - apiGroups: [servicefunctionchain.polito.it]
    resources: [servicefunctionchains, loadbalancers]
    verbs: [create, delete, get, list, patch, update, watch]

  - apiGroups: [servicefunctionchain.polito.it]
    resources: [servicefunctionchains/finalizers, loadbalancers/finalizers]
    verbs: [update]

  - apiGroups: [servicefunctionchain.polito.it]
    resources: [servicefunctionchains/status, loadbalancers/status]
    verbs: [get, patch, update]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: manager-role
subjects:
- kind: ServiceAccount
  name: controller-manager
  namespace: operator-system